#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s

scrape_configs:
  - job_name: "folha360-webapi"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["folha360-webapi:8080"]
