// <auto-generated />
using System;
using Folha360.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Folha360.Infrastructure.Migrations
{
    [DbContext(typeof(Folha360DbContext))]
    [Migration("20260606174031_AddEventosTrabalhistas")]
    partial class AddEventosTrabalhistas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cbo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("cbo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("SalarioBaseMaximo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario_base_maximo");

                    b.Property<decimal?>("SalarioBaseMinimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario_base_minimo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cargo");

                    b.HasIndex("Cbo")
                        .HasDatabaseName("ix_cargo_cbo");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_cargo_empresa_id");

                    b.ToTable("cargo", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Convenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Operadora")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operadora");

                    b.Property<decimal>("PercentualEmpresa")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentual_empresa");

                    b.Property<decimal>("PercentualFuncionario")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentual_funcionario");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_mensal");

                    b.HasKey("Id")
                        .HasName("pk_convenio");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_convenio_empresa_id");

                    b.ToTable("convenio", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DependenteIrrf")
                        .HasColumnType("boolean")
                        .HasColumnName("dependente_irrf");

                    b.Property<bool>("DependenteSalarioFamilia")
                        .HasColumnType("boolean")
                        .HasColumnName("dependente_salario_familia");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("GrauParentesco")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grau_parentesco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("PensaoAlimenticiaPercentual")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pensao_alimenticia_percentual");

                    b.Property<decimal?>("PensaoAlimenticiaValor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pensao_alimenticia_valor");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dependente");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_dependente_funcionario_id");

                    b.ToTable("dependente", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArquivoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arquivo_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao");

                    b.Property<DateOnly?>("DataValidade")
                        .HasColumnType("date")
                        .HasColumnName("data_validade");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orgao_emissor");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("UfEmissor")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf_emissor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_documento");

                    b.HasIndex("FuncionarioId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_documento_funcionario_id_tipo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("documento", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassificacaoTributaria")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("classificacao_tributaria");

                    b.Property<string>("Cnae")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cnae");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CnpjMatriz")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_matriz");

                    b.Property<string>("CodigoTerceiros")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_terceiros");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EnderecoBairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_bairro");

                    b.Property<string>("EnderecoCep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("endereco_cep");

                    b.Property<string>("EnderecoComplemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_complemento");

                    b.Property<string>("EnderecoLogradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco_logradouro");

                    b.Property<string>("EnderecoMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_municipio");

                    b.Property<string>("EnderecoNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("EnderecoUf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("endereco_uf");

                    b.Property<string>("Fpas")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fpas");

                    b.Property<string>("MatrizFilial")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("matriz_filial");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("RegimeTributario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regime_tributario");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_empresa");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresa_cnpj")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("RazaoSocial")
                        .HasDatabaseName("ix_empresa_razao_social");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_empresa_tenant_id");

                    b.ToTable("empresa", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("CpfHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cpf_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateOnly?>("DataDesligamento")
                        .HasColumnType("date")
                        .HasColumnName("data_desligamento");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("EnderecoBairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_bairro");

                    b.Property<string>("EnderecoCep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("endereco_cep");

                    b.Property<string>("EnderecoComplemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_complemento");

                    b.Property<string>("EnderecoLogradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco_logradouro");

                    b.Property<string>("EnderecoMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_municipio");

                    b.Property<string>("EnderecoNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("EnderecoUf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("endereco_uf");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_civil");

                    b.Property<int?>("JornadaHorasSemanais")
                        .HasColumnType("integer")
                        .HasColumnName("jornada_horas_semanais");

                    b.Property<Guid>("LotacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lotacao_id");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_mae");

                    b.Property<string>("NomePai")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_pai");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario_base");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoContrato")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_contrato");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_funcionario");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("ix_funcionario_cargo_id");

                    b.HasIndex("CpfHash")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionario_cpf_hash")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_funcionario_empresa_id");

                    b.HasIndex("LotacaoId")
                        .HasDatabaseName("ix_funcionario_lotacao_id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_funcionario_nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nome"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nome"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_funcionario_status");

                    b.ToTable("funcionario", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.HorarioTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CargaHorariaDiaria")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria_diaria");

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria_semanal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<TimeOnly?>("FimIntervalo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fim_intervalo");

                    b.Property<TimeOnly>("FimJornada")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fim_jornada");

                    b.Property<TimeOnly?>("InicioIntervalo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("inicio_intervalo");

                    b.Property<TimeOnly>("InicioJornada")
                        .HasColumnType("time without time zone")
                        .HasColumnName("inicio_jornada");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<int>("ToleranciaAtrasoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tolerancia_atraso_minutos");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_horario_trabalho");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_horario_trabalho_empresa_id_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("horario_trabalho", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Lotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("TipoEsocial")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_esocial");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lotacao");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_lotacao_empresa_id_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("lotacao", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Rubrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FormulaCalculo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("formula_calculo");

                    b.Property<bool>("IncideAvisoPrevio")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_aviso_previo");

                    b.Property<bool>("IncideContribuicaoSindical")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_contribuicao_sindical");

                    b.Property<bool>("IncideDecimoTerceiro")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_decimo_terceiro");

                    b.Property<bool>("IncideFerias")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_ferias");

                    b.Property<bool>("IncideFgts")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_fgts");

                    b.Property<bool>("IncideInss")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_inss");

                    b.Property<bool>("IncideIrrf")
                        .HasColumnType("boolean")
                        .HasColumnName("incide_irrf");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("natureza");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_exibicao");

                    b.Property<string>("TipoEsocial")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_esocial");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rubrica");

                    b.HasIndex("Natureza")
                        .HasDatabaseName("ix_rubrica_natureza");

                    b.HasIndex("TipoEsocial")
                        .HasDatabaseName("ix_rubrica_tipo_esocial");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_rubrica_empresa_id_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("rubrica", "public");
                });

            modelBuilder.Entity("Folha360.Cadastros.Domain.Entities.Sindicato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<decimal>("ContribuicaoAssistencialPercentual")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("contribuicao_assistencial_percentual");

                    b.Property<decimal>("ContribuicaoSindicalPercentual")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("contribuicao_sindical_percentual");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sindicato");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_sindicato_empresa_id_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("sindicato", "public");
                });

            modelBuilder.Entity("Folha360.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_data");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_data");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schema_name");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("ix_audit_log_changed_at");

                    b.HasIndex("TableName", "RecordId")
                        .HasDatabaseName("ix_audit_log_table_name_record_id");

                    b.ToTable("audit_log", "public");
                });

            modelBuilder.Entity("Folha360.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schema_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("SchemaName")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_schema_name");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_tenant_id");

                    b.ToTable("tenant", "public");
                });

            modelBuilder.Entity("Folha360.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.ToTable("usuario", "public");
                });

            modelBuilder.Entity("Folha360.Eventos.Domain.Entities.Admissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int?>("PeriodoExperienciaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_experiencia_meses");

                    b.Property<decimal>("SalarioInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario_inicial");

                    b.Property<int>("TipoContrato")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_contrato");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XmlContent")
                        .HasColumnType("text")
                        .HasColumnName("xml_content");

                    b.HasKey("Id")
                        .HasName("pk_admissao");

                    b.HasIndex("DataAdmissao")
                        .HasDatabaseName("ix_admissao_data_admissao");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_admissao_empresa_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_admissao_funcionario_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("admissao", "public");
                });

            modelBuilder.Entity("Folha360.Eventos.Domain.Entities.Afastamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cid")
                        .HasColumnType("text")
                        .HasColumnName("cid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataFimEfetiva")
                        .HasColumnType("date")
                        .HasColumnName("data_fim_efetiva");

                    b.Property<DateOnly>("DataFimPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_fim_prevista");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("TipoAfastamento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_afastamento");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XmlContent")
                        .HasColumnType("text")
                        .HasColumnName("xml_content");

                    b.HasKey("Id")
                        .HasName("pk_afastamento");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_afastamento_empresa_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_afastamento_funcionario_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("afastamento", "public");
                });

            modelBuilder.Entity("Folha360.Eventos.Domain.Entities.AlteracaoContratual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CamposAlterados")
                        .HasColumnType("jsonb")
                        .HasColumnName("campos_alterados");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataAlteracao")
                        .HasColumnType("date")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_novo");

                    b.Property<string>("XmlContent")
                        .HasColumnType("text")
                        .HasColumnName("xml_content");

                    b.HasKey("Id")
                        .HasName("pk_alteracao_contratual");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_alteracao_contratual_empresa_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_alteracao_contratual_funcionario_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("alteracao_contratual", "public");
                });

            modelBuilder.Entity("Folha360.Eventos.Domain.Entities.Desligamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataDesligamento")
                        .HasColumnType("date")
                        .HasColumnName("data_desligamento");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("MotivoDesligamento")
                        .HasColumnType("integer")
                        .HasColumnName("motivo_desligamento");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerbasRescisorias")
                        .HasColumnType("jsonb")
                        .HasColumnName("verbas_rescisorias");

                    b.Property<string>("XmlContent")
                        .HasColumnType("text")
                        .HasColumnName("xml_content");

                    b.HasKey("Id")
                        .HasName("pk_desligamento");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_desligamento_empresa_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_desligamento_funcionario_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("desligamento", "public");
                });

            modelBuilder.Entity("Folha360.Eventos.Domain.Entities.Ferias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DiasGozo")
                        .HasColumnType("integer")
                        .HasColumnName("dias_gozo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<DateOnly>("PeriodoAquisitivoFim")
                        .HasColumnType("date")
                        .HasColumnName("periodo_aquisitivo_fim");

                    b.Property<DateOnly>("PeriodoAquisitivoInicio")
                        .HasColumnType("date")
                        .HasColumnName("periodo_aquisitivo_inicio");

                    b.Property<int>("TipoFerias")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_ferias");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XmlContent")
                        .HasColumnType("text")
                        .HasColumnName("xml_content");

                    b.HasKey("Id")
                        .HasName("pk_ferias");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_ferias_empresa_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_ferias_funcionario_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("ferias", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
